# Generated by Django 3.1.6 on 2021-02-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('post_image', models.ImageField(upload_to='post_image/')),
                ('post_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
